name: cleanup-files
description: "Cleans up files on the local system to reduce disk pressure"

runs:
  using: composite
  steps:
    - run: |
        lsblk -f

        sudo rm -rf zarf-sbom /tmp/zarf-*
        sudo env "PATH=$PATH" CI=true make delete-packages
        sudo rm -rf /usr/share/dotnet
        sudo build/zarf tools clear-cache
        sudo docker system prune --all --force

        lsblk -f
      shell: bash
