---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: podinfo-helm
  namespace: flux-system
spec:
  interval: 30s
  url: oci://ghcr.io/stefanprodan/charts/podinfo
  ref:
    tag: 6.4.0
