apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo-oci
  namespace: flux-system
spec:
  interval: 5m0s
  releaseName: podinfo-oci
  chartRef:
    kind: OCIRepository
    name: podinfo-helm
  targetNamespace: podinfo-helm-oci
