# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2
pro: true

nightly:
  # Allows you to change the version of the generated nightly release.
  version_template: "{{ .Version }}"

  # Tag name to create if publish_release is enabled.
  tag_name: nightly

  # Whether to publish a release or not.
  publish_release: true

  # This allows you to keep a single nightly.
  keep_single_release: true

includes:
  - from_file:
      path: ./.goreleaser.yaml
