version: 2

before:
  hooks:
    - go mod tidy

# Build a universal macOS binary
universal_binaries:
  - replace: false

# Build the different combination of goos/arch binaries
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    ldflags:
      - -s -w -X github.com/zarf-dev/zarf/src/config.CLIVersion={{.Tag}}
      - -X k8s.io/component-base/version.gitVersion=v{{.Env.K8S_MODULES_MAJOR_VER}}.{{.Env.K8S_MODULES_MINOR_VER}}.{{.Env.K8S_MODULES_PATCH_VER}}
      - -X k8s.io/component-base/version.gitCommit={{.FullCommit}}
      - -X k8s.io/component-base/version.buildDate={{.Date}}
      - -X helm.sh/helm/v3/pkg/lint/rules.k8sVersionMajor={{.Env.K8S_MODULES_MAJOR_VER}}
      - -X helm.sh/helm/v3/pkg/lint/rules.k8sVersionMinor={{.Env.K8S_MODULES_MINOR_VER}}
      - -X helm.sh/helm/v3/pkg/chartutil.k8sVersionMajor={{.Env.K8S_MODULES_MAJOR_VER}}
      - -X helm.sh/helm/v3/pkg/chartutil.k8sVersionMinor={{.Env.K8S_MODULES_MINOR_VER}}
      - -X github.com/derailed/k9s/cmd.version={{.Env.K9S_VERSION}}
      - -X github.com/google/go-containerregistry/cmd/crane/cmd.Version={{.Env.CRANE_VERSION}}
      - -X github.com/zarf-dev/zarf/src/cmd.syftVersion={{.Env.SYFT_VERSION}}
      - -X github.com/zarf-dev/zarf/src/cmd.archiverVersion={{.Env.ARCHIVER_VERSION}}
      - -X github.com/zarf-dev/zarf/src/cmd.helmVersion={{.Env.HELM_VERSION}}
    goarch:
      - amd64
      - arm64

# Save the built artifacts as binaries (instead of wrapping them in a tarball)
archives:
  - formats: [ 'binary' ]
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{- title .Os }}_{{ .Arch }}"

# generate a sha256 checksum of all release artifacts
# NOTE: We are explicitly adding the init-packages that are built prior to GoReleaser stage in the GitHub Actions workflow
checksum:
  name_template: "checksums.txt"
  extra_files:
    - glob: ./build/zarf-init-*
  algorithm: sha256

# generate sboms for each binary artifact
sboms:
  - artifacts: binary
    documents:
      - "sbom_{{ .ProjectName }}_{{ .Tag }}_{{- title .Os }}_{{ .Arch }}.sbom"

snapshot:
  version_template: "{{ incpatch .Version }}-snapshot"

# Use the auto-generated changelog github provides
changelog:
  use: github-native

# Generate a GitHub release and publish the release for the tag
# NOTE: We are explicitly adding the init-packages that are built prior to GoReleaser stage in the GitHub Actions workflow
release:
  github:
    owner: zarf-dev
    name: zarf
  prerelease: auto
  mode: append
  extra_files:
    - glob: ./build/zarf-init-*

# Update the 'generic' brew formula and create a versioned brew formula for artifacts from this release
brews:
  - name: "{{ .Env.BREW_NAME }}"
    repository:
      owner: defenseunicorns
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
      branch: "{{ .ProjectName }}-{{ .Tag }}"
      pull_request:
        enabled: true
        base:
          branch: main
          owner: defenseunicorns
          name: homebrew-tap

    commit_msg_template: "build(release): upgrade {{ .ProjectName }} to {{ .Tag }}"
    homepage: "https://zarf.dev/"
    description: "DevSecOps for Airgap"

  # NOTE: We are using .Version instead of .Tag because homebrew has weird semver parsing rules and won't be able to
  #       install versioned releases that has a `v` character before the version number.
  - name: "zarf@{{ .Version }}"
    repository:
      owner: defenseunicorns
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
      branch: "{{ .ProjectName }}-{{ .Tag }}"
      pull_request:
        enabled: true
        base:
          branch: main
          owner: defenseunicorns
          name: homebrew-tap
    commit_msg_template: "build(release): {{ .ProjectName }}@{{ .Tag }}"
    homepage: "https://zarf.dev/"
    description: "DevSecOps for Airgap"
