# kind: Cluster
# apiVersion: kind.x-k8s.io/v1alpha4
# networking:
#   ipFamily: ipv6


kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  kubeProxyMode: "nftables"
  # ipFamily: ipv6

## Get nodeip
## pick the first node (kind is single-node unless you asked for more)
# NODE=$(kubectl get nodes -o name | head -1)

# # grab its InternalIP that looks like an IPv6 address
# NODE_IP=$(kubectl get $NODE \
#   -o jsonpath='{.status.addresses[?(@.type=="InternalIP")].address}')

# echo "Node IP is: $NODE_IP"
