apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.appName }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    replicas: "{{ .Values.replicaCount }}"
data:
  # Test basic mappings
  app-name: "{{ .Values.appName }}"
  replica-count: "{{ .Values.replicaCount }}"
  image-tag: "{{ .Values.image.tag }}"

  # Test nested object mapping
  database-host: "{{ .Values.config.database.host }}"
  database-port: "{{ .Values.config.database.port }}"

  # Test default values (not mapped)
  log-level: "{{ .Values.config.app.logLevel }}"
  debug-mode: "{{ .Values.config.app.debug }}"

  # Test resource values
  cpu-limit: "{{ .Values.resources.limits.cpu }}"
  memory-limit: "{{ .Values.resources.limits.memory }}"
