apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: nginx
  labels:
    app: nginx
data:
  01_http.conf: |
    add_header X-Kubernetes-Pod $hostname;
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Welcome to {{ .Values.site.name }}!</title>
      <style>
        {{ .Values.site.style }}
      </style>
    </head>
    <body>
    <!-- Test two separate variables on the same line -->
    <h1>Welcome to the {{ .Values.site.name }}!</h1><h2>Brought to you by {{ .Values.site.organization }}.</h2>
    <p>Below is a Terraform File templated by Zarf</p>
    <pre>
          {{ .Values.terraform.path }}
        </pre>
    <pre>File SHASUM: {{ .Values.terraform.shasum }}</pre>
    {{ .Values.site.optional-footer }}
    </body>
    </html>
