name: install-tools
description: "Install pipeline tools"

runs:
  using: composite
  steps:
    - uses: sigstore/cosign-installer@cad07c2e89fa2edd6e2d7bab4c1aa38e53f76003 # v4.1.1
      with:
        cosign-release: 'v3.0.6'

    - uses: anchore/sbom-action/download-syft@e22c389904149dbc22b58101806040fa8d37a610 # v0.24.0
      with:
        syft-version: 'v1.42.3'

    - uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
      with:
        version: 'v0.34.0'
