name: save-logs
description: "Save debug logs"

inputs:
  suffix:
    description: 'Suffix to append to the debug log'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Fix log permissions
      run: |
        sudo chown $USER /tmp/zarf-*.log || echo ""
      shell: bash

    - uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
      with:
        name: debug-log${{ inputs.suffix }}
        path: /tmp/zarf-*.log
