apiVersion: v1
kind: Pod
metadata:
{{- with .Values.injector.nodeport.pod.metadata }}
{{ toYaml . | nindent 2 }}
{{- end }}
spec:
{{- with .Values.injector.nodeport.pod.spec }}
{{ toYaml . | nindent 2 }}
{{- end }}
  containers:
    - name: injector
{{- with .Values.injector.nodeport.pod.container }}
{{ toYaml . | nindent 6 }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
{{- with .Values.injector.nodeport.service.metadata }}
{{ toYaml . | nindent 2 }}
{{- end }}
spec:
{{- with .Values.injector.nodeport.service.spec }}
{{ toYaml . | nindent 2 }}
{{- end }}
