# Derive image settings from the packaged image, including build-time overrides.
{{- range .Pkg.Components }}
{{- if eq .Service "agent" }}
{{- $image := (index .Images 0).Name }}
# FIXME: can we make this simpler, additional functions might help?
image:
  repository: {{ printf "%s/%s" $.State.Registry.Address (regexReplaceAll ":[^:]+$" (regexReplaceAll "^[^/]+/" $image "") "") | quote }}
  tag: {{ regexFind "[^:]+$" $image | quote }}
{{- end }}
{{- end }}
secret:
  tlsCrt: {{ .State.Agent.Cert | quote }}
  tlsKey: {{ .State.Agent.Key | quote }}
