# Earthfile
  
go-deps: 
  FROM registry1.dso.mil/ironbank/google/golang/golang-1.16
  WORKDIR /payload

  # Cache the test suite
  RUN go get gotest.tools/gotestsum 

  COPY go.* .

  # Cache dep loading
  RUN go mod download

go-test:
  FROM +go-deps 
  # Needed to prevent go test from choking
  ENV CGO_ENABLED 0

  # Add all src files
  COPY main.go .
  COPY -dir cmd .
  COPY -dir internal .

  # Tests
  RUN gotestsum

build:
  FROM +go-test

  RUN go build -o shift-pack main.go

  SAVE ARTIFACT shift-pack
