apiVersion: zarf.dev/v1beta1
kind: ZarfComponentConfig
metadata:
  name: zarf-agent
  description: |
    A Kubernetes mutating webhook to enable automated URL rewriting for container
    images and git repository references in Kubernetes manifests. This prevents
    the need to manually update URLs from their original sources to the Zarf-managed
    docker registry and git server.

values:
  files:
    - values.yaml
  schema: values-schema.json

component:
  services:
    isAgent: true
  charts:
    - name: zarf-agent
      releaseName: zarf-d2db14ef40305397791454e883b26fc94ad9615d
      namespace: zarf
      local:
        path: ../../zarf-agent/chart
      valuesFiles:
        - ../../zarf-agent/agent-values.yaml
