apiVersion: v1
kind: Service
metadata:
  name: nginx-connect
  namespace: nginx
  annotations:
    zarf.dev/connect-description: "Launch the nginx static site."
  labels:
    zarf.dev/connect-name: nginx
    zarf.dev/example-var: {{ .Variables.EXAMPLE_VAR }}
    zarf.dev/example-const: {{ .Constants.EXAMPLE_CONST }}
spec:
  ports:
  - port: 8080
    name: http
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
