# Constants are defined on package create and do not change on deploy
# This demonstrates setting the nginx version to bake into the package using a package variable (PKG_TMPL)
site:
  # The name of the site you are deploying
  name: "Zarf Values Example Website"
  # Sets the CSS styles for the site, and provides an example of a multi-line value
  styles: >-
    body { font-family: sans-serif; color: white; background: #0a0e2e; }
    pre { color: white; background: black; }
  # The organization providing the site
  organization: "Zarf-Dev"
  # The footer to be added to the site, overrides the default with whatever you want.
  footer: ""

# terraform.path sets a filepath for a terraform file to be used as the contents of a template
terraform:
  path: "modified-terraform.tf"
  aws:
    # Modifies modified-terraform.tf file
    region: "us-east-1"

# TODO(mkcp): It would be good to have an example that leverages go-templates' more programmatic features. e.g
# loops, pipelines, functions (quote, upper, lower), repeat, default,

