# Generate the Zarf CLI docs
printf "Generating CLI docs\n"
ZARF_CONFIG=hack/empty-config.toml go run main.go internal generate-cli-docs

BUILT_BY="<!-- Auto-generated by hack\/gen-cli-docs.sh -->"
SEPERATOR="---"
TYPE="type: docs"

# The GenMarkdownTree function from cobra/docs starts the headers at H2.
# This converts the H2 to Hugo frontmatter and reduces all other headers by one level.

printf "Creating frontmatter from auto-generated title\n"
for FILE in $(find docs/2-the-zarf-cli/100-cli-commands -name "*.md")
do
  sed -i.bak "1s/^/${SEPERATOR}\n/" ${FILE}
  sed -i.bak "s/^## \(.*\)/title: \1\n${TYPE}\n---\n\n${BUILT_BY}\n/" ${FILE}
  sed -i.bak 's/^##/#/g' ${FILE}
  truncate -s -1 ${FILE}
  rm ${FILE}.bak
done

# Create the top menu label for the sidebar menu
printf "Generating sidebar menu label\n"
MENU_LABEL='title: CLI Commands'
printf "%s\n%s\ntype: docs\n%s\n\n%s\n" "${SEPERATOR}" "${MENU_LABEL}" "${SEPERATOR}" "${BUILT_BY}" > docs/2-the-zarf-cli/100-cli-commands/_index.md

