// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    { type: 'autogenerated', dirName: 'docs' },
  ],
}

module.exports = sidebars
