apiVersion: zarf.dev/v1beta1
kind: ZarfComponentConfig
metadata:
  name: zarf-injector
  version: "[[ .cli.version ]]"
  description: Inject the seed registry into a running cluster pod
variant:
  architecture: arm64
component:
  service: injector
  files:
    - source: https://github.com/zarf-dev/zarf-injector/releases/download/v0.3.0/zarf-injector-arm64
      destination: "###ZARF_TEMP###/zarf-injector"
      checksum: 7a677809accc0d3d9b1cddc8d6be07ebf0a883a1db887e50828bb3df0e824577
      executable: true
