apiVersion: zarf.dev/v1beta1
kind: ZarfComponentConfig
metadata:
  name: git-server
  description: |
    Deploys Gitea to provide git repositories for Kubernetes configurations.
    Required for GitOps deployments if no other git server is available.

values:
  files:
    - values.yaml
  schema: values-schema.json

component:
  manifests:
    - name: git-connect
      namespace: zarf
      files:
        - connect.yaml
  charts:
    - name: gitea
      releaseName: zarf-gitea
      namespace: zarf
      oci:
        url: oci://registry-1.docker.io/giteacharts/gitea
        version: 12.3.0
      valuesFiles:
        - gitea-values.yaml
      values:
        - sourcePath: ".agent"
          targetPath: "."
  actions:
    onDeploy:
      before:
        - cmd: ./zarf internal update-gitea-pvc
          setVariables:
            - name: GIT_SERVER_CREATE_PVC
          mute: true
      after:
        - cmd: ./zarf internal create-read-only-gitea-user
          retries: 3
          maxTotalSeconds: 60
          description: Create the read-only Gitea user
        - cmd: ./zarf internal create-artifact-registry-token
          retries: 3
          maxTotalSeconds: 60
          description: Create an artifact registry token
      onFailure:
        - cmd: ./zarf internal update-gitea-pvc --rollback
