{{- range .Pkg.Components }}
{{- if eq .Service "registry" }}
{{- $registry := (index .Images 0).Name }}
{{- $proxy := (index .Images 1).Name }}
image:
  repository: {{ printf "%s/%s" $.State.Registry.Address (regexReplaceAll ":[^:]+$" (regexReplaceAll "^[^/]+/" $registry "") "") | quote }}
  tag: {{ regexFind "[^:]+$" $registry | quote }}
proxy:
  image:
    repository: {{ printf "%s/%s" $.State.Registry.SeedAddress (regexReplaceAll ":[^:]+$" (regexReplaceAll "^[^/]+/" $proxy "") "") | quote }}
    tag: {{ regexFind "[^:]+$" $proxy | quote }}
  registry:
    image:
      repository: {{ printf "%s/%s" $.State.Registry.SeedAddress (regexReplaceAll ":[^:]+$" (regexReplaceAll "^[^/]+/" $registry "") "") | quote }}
{{- end }}
{{- end }}
