{{- range .Pkg.Components }}
{{- if eq .Service "seed-registry" }}
{{- $registry := (index .Images 0).Name }}
{{- $proxy := (index .Images 1).Name }}
image:
  repository: {{ printf "%s/%s" $.State.Registry.SeedAddress (imageRepository $registry) | quote }}
  tag: {{ imageTag $registry | quote }}
proxy:
  image:
    repository: {{ printf "%s/%s" $.State.Registry.SeedAddress (imageRepository $proxy) | quote }}
    tag: {{ imageTag $proxy | quote }}
  registry:
    image:
      repository: {{ printf "%s/%s" $.State.Registry.SeedAddress (imageRepository $registry) | quote }}
{{- end }}
{{- end }}
