{{ if eq .Values.service.hostNetwork "true" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: zarf-registry-proxy
spec:
  selector:
    matchLabels:
      app: zarf-registry-proxy
  template:
    metadata:
      labels:
        app: zarf-registry-proxy
        # Don't mutate this pod
        zarf.dev/agent: ignore
    spec:
      containers:
        - args:
          {{ if eq .Values.service.ipv6Only "true" }}
            - tcp6-listen:{{ .Values.service.nodePort }},reuseaddr,fork
            - tcp6:{{ template "docker-registry.fullname" . }}:5000
          {{- else }}
            - tcp4-listen:{{ .Values.service.nodePort }},reuseaddr,fork
            - tcp4:{{ template "docker-registry.fullname" . }}:5000
          {{- end }}
          image: "{{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag }}"
          imagePullPolicy: IfNotPresent
          name: zarf-registry-proxy
          ports:
            - containerPort: {{ .Values.service.nodePort }}
            {{ if ne .Values.service.ipv6Only "true" }}
              hostPort: {{ .Values.service.nodePort }}
              hostIP: "127.0.0.1"
            {{- end }}
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
    # IPV6 does not support rewriting packets to localhost so it needs to use host network over hostport
    {{ if eq .Values.service.ipv6Only "true" }}
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
    {{- end }}
{{- end }}
