{{- if .Values.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docker-registry.fullname" . }}-tls
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    app: {{ template "docker-registry.name" . }}
type: Opaque
stringData:
  domain.crt: |
    {{- .Values.tls.cert | nindent 4 }}
  domain.key: |
    {{- .Values.tls.key | nindent 4 }}
{{- end }}
