apiVersion: zarf.dev/v1beta1
kind: ZarfComponentConfig
metadata:
  name: zarf-seed-registry
  description: |
    Deploys the Zarf Registry using the registry image provided by the Zarf Injector.

variables:
  - name: REGISTRY_EXISTING_PVC
    description: "Optional: Use an existing PVC for the registry instead of creating a new one. If this is set, the REGISTRY_PVC_SIZE variable will be ignored."
    default: ""

  - name: REGISTRY_PVC_ENABLED
    description: Toggle the creation and use of a PVC off/on
    default: "true"

  - name: REGISTRY_PVC_SIZE
    description: The size of the persistent volume claim for the registry
    default: 20Gi

  - name: REGISTRY_PVC_ACCESS_MODE
    description: The access mode of the persistent volume claim for the registry
    default: ReadWriteOnce

  - name: REGISTRY_CPU_REQ
    description: The CPU request for the registry
    default: 100m

  - name: REGISTRY_MEM_REQ
    description: The memory request for the registry
    default: 256Mi

  - name: REGISTRY_CPU_LIMIT
    description: The CPU limit for the registry
    default: "3"

  - name: REGISTRY_MEM_LIMIT
    description: The memory limit for the registry
    default: "2Gi"

  - name: REGISTRY_HPA_MIN
    description: The minimum number of registry replicas
    default: "1"

  - name: REGISTRY_HPA_MAX
    description: The maximum number of registry replicas
    default: "5"

  - name: REGISTRY_HPA_ENABLE
    description: Enable the Horizontal Pod Autoscaler for the registry
    default: "true"

  - name: REGISTRY_CA_BUNDLE
    description: Filepath to a bundle of trusted certificates to mount into the registry container
    default: ""
    autoIndent: true
    type: file

  - name: REGISTRY_EXTRA_ENVS
    description: Array of additional environment variables passed to the registry container
    default: ""
    autoIndent: true

  - name: REGISTRY_OTEL_EXPORTER
    description: set the opentelemetry exporter
    default: "none"

  - name: REGISTRY_CREATE_SERVICE_ACCOUNT
    description: Toggle the creation of a new service account for the registry
    default: "false"

  - name: REGISTRY_SERVICE_ACCOUNT_NAME
    description: The name of the service account to use. If not set and create is true, a name is generated using fullname template
    default: ""

  - name: REGISTRY_SERVICE_ACCOUNT_ANNOTATIONS
    description: Map of annotations to add to the created service account
    default: ""
    autoIndent: true

  - name: REGISTRY_AFFINITY_ENABLE
    description: Enable pod affinity for the registry
    default: "true"

  - name: REGISTRY_AFFINITY_CUSTOM
    description: Custom pod affinity yaml block for the registry
    default: ""
    autoIndent: true

  - name: REGISTRY_TOLERATIONS
    description: Custom tolerations array for the registry
    default: ""
    autoIndent: true

  - name: REGISTRY_NODE_SELECTOR
    description: Custom node selector map for the registry
    default: ""
    autoIndent: true

  - name: PROXY_TOLERATIONS
    description: Custom tolerations array for the registry proxy
    default: ""
    autoIndent: true

  - name: REGISTRY_HPA_AUTO_SIZE
    description: Enable to set min and max replicas based on amount of nodes
    default: "false"

  - name: REGISTRY_HPA_TARGET_CPU
    description: The target CPU utilization percentage for the registry
    default: "80"

  - name: HOST_NETWORK_PROXY
    description: Decides if host port or host network should be used with the registry proxy
    default: "false"

  - name: REGISTRY_SECURITY_CONTEXT_RUN_AS_USER
    description: The user ID to run the registry as
    default: "1000"

  - name: REGISTRY_SECURITY_CONTEXT_FS_GROUP
    description: The filesystem group ID to run the registry as
    default: "2000"

  - name: REGISTRY_SECURITY_CONTEXT_RUN_AS_GROUP
    description: The group ID to run the registry as
    default: "2000"

component:
  services:
    isRegistry: true
  charts:
    - name: docker-registry
      releaseName: zarf-docker-registry
      namespace: zarf
      local:
        path: ../../zarf-registry/chart
      valuesFiles:
        - ../../zarf-registry/registry-values.yaml
        - ../../zarf-registry/registry-values-seed.yaml
  images:
    - name: "[[ .REGISTRY_IMAGE_DOMAIN ]][[ .REGISTRY_IMAGE ]]:[[ .REGISTRY_IMAGE_TAG ]]"
    - name: "[[ .PROXY_IMAGE_DOMAIN ]][[ .PROXY_IMAGE ]]:[[ .PROXY_IMAGE_TAG ]]"
