---
# yaml-language-server: $schema=https://raw.githubusercontent.com/eksctl-io/eksctl/v0.202.0/pkg/apis/eksctl.io/v1alpha5/assets/schema.json
# eksctl create cluster --config-file=eks.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: "###ZARF_VAR_EKS_CLUSTER_NAME###"
  region: "###ZARF_VAR_EKS_CLUSTER_REGION###"
  tags:
    PermissionsBoundary: "###ZARF_VAR_PERMISSIONS_BOUNDARY_TAG###"

iam:
  withOIDC: true
  serviceRolePermissionsBoundary: "###ZARF_VAR_PERMISSIONS_BOUNDARY_ARN###"

addons:
  - name: aws-ebs-csi-driver
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
    permissionsBoundary: "###ZARF_VAR_PERMISSIONS_BOUNDARY_ARN###"
    tags:
      PermissionsBoundary: "###ZARF_VAR_PERMISSIONS_BOUNDARY_TAG###"

  - name: vpc-cni
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
    permissionsBoundary: "###ZARF_VAR_PERMISSIONS_BOUNDARY_ARN###"
    tags:
      PermissionsBoundary: "###ZARF_VAR_PERMISSIONS_BOUNDARY_TAG###"

managedNodeGroups:
- instanceType: "###ZARF_VAR_EKS_INSTANCE_TYPE###"
  name: "###ZARF_VAR_EKS_CLUSTER_NAME###-ng"
  minSize: 3
  maxSize: 6
  spot: true
  tags:
    PermissionsBoundary: "###ZARF_VAR_PERMISSIONS_BOUNDARY_TAG###"
  iam:
    instanceRolePermissionsBoundary: "###ZARF_VAR_PERMISSIONS_BOUNDARY_ARN###"
