animals:
  scorpion: iridescent
  camelSpider: matte
# Dummy TLS CA showcasing multiline values in a values file.
tls:
  ca: |-
    -----BEGIN CERTIFICATE-----
    MIIDWjCCAkKgAwIBAgIRAKX5F/lce63a8HD+hATcOw0wDQYJKoZIhvcNAQELBQAw
    NzEXMBUGA1UEChMOWmFyZiBDb21tdW5pdHkxHDAaBgNVBAMTE2NhLnByaXZhdGUu
    emFyZi5kZXYwHhcNMjYwNzMxMTYzNjEzWhcNMjcwODEwMTYzNjEzWjA3MRcwFQYD
    VQQKEw5aYXJmIENvbW11bml0eTEcMBoGA1UEAxMTY2EucHJpdmF0ZS56YXJmLmRl
    djCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKqY0okwGGk755NU//Dx
    KRBDrN2bjGJYYyeKQORunCwTduY8ROD6wvE1Cfh+tReQdvvVRsmvgQqJxBHOFy5V
    ZEhAmJePtkMvoUA0ZxIe4Hnws5M67WQjsYWSKK+1hzCp/37Y/oVxO0rzn4IFgr0z
    cpf2r4zRKgzDFMUOqCvCvDy7loLs9+N/gG8+6PwZk8sozBbFc8HrvmzVrsaJRMf5
    HsSomEuMoxZ21G+EqjJmJqoRKR21xjaWALonhECk2q4pbHwiA/uTeyBT/ZD+/i4L
    BTP8FCflKBR3/stFRqNbTFeHofN0JR1TPr/RmY3IAc2ybaN3sX7Z/tHmLoj4c+KO
    2nkCAwEAAaNhMF8wDgYDVR0PAQH/BAQDAgKEMB0GA1UdJQQWMBQGCCsGAQUFBwMB
    BggrBgEFBQcDAjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSAuqjNxPbA+rUJ
    2BSzq+LbuItG7DANBgkqhkiG9w0BAQsFAAOCAQEASrN3E/0t1AP8EeDZElxAetmw
    nvo8f4GiewmP780XPIj3OEeAns9TAXvj1MF2l4+v+6DOAhk3HUuHiP6x8zCkdewO
    kgf+dDneMrUl2ZIdjNT75zHptwuxxY4E2SBHJ7MDsUE2UeG7vgbi75NFW4mBBh76
    VzT/FvsqpINJBRV/AKBTJMxxsrsOQ3t6GdppryL1VLlBeRFBPfev4IJF7/TSexfX
    y9/Vzl6ZUm8vmzkpG80Jog9Fqg7LC68imuISqTzsHQ0I/UKQsymvlAsw7kLbxjWf
    5EYDmpvaUP8EpGWx6VMxs9LajYwFqmt7+ZE2FWxWxwepL03WC+Lv8R7OWGM4Zg==
    -----END CERTIFICATE-----
