apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-configmap
  namespace: zarf
  labels:
    app: zarf
data:
  templateme.properties: |
    scorpion={{ .Values.animals.scorpion }}
    camel_spider={{ .Values.animals.camelSpider }}
    cow=moo
  tls-ca: |-
{{ .Values.tls.ca | indent 4 }}
