---
apiVersion: v1
kind: Service
metadata:
  name: zarf-docs
  annotations:
    zarf.dev/connect-description: "View the Zarf docs site served from an image volume"
  labels:
    app: zarf-docs
    zarf.dev/connect-name: docs
spec:
  selector:
    app: zarf-docs
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
