# Constants are defined on package create and do not change on deploy
# This demonstrates setting the nginx version to bake into the package using a package variable (PKG_TMPL)
site:
  # The name of the site you are deploying
  name: "Zarf Values Example Website"
  # Sets the CSS styles for the site, and provides an example of a multi-line value
  styles: >-
    body { font-family: sans-serif; color: white; background: #0a0e2e; }
    pre { color: white; background: black; }
  # The organization providing the site
  organization: "Zarf-Dev"
  # The footer to be added to the site, overrides the default with whatever you want.
  footer: ""
  # Additional metadata for sprig examples
  title: "my awesome app"
  message: "hello world from zarf"

# Application deployment configuration
app:
  environment: "production"
  replicas: 3
  # Configuration data that can be hashed for integrity checks
  config_data: "important application configuration data"
  # Optional field to demonstrate default values
  optional_setting: ""  # Will use default value in templates
  required_setting: "configured value"
  # List of supported features for list function examples
  features:
    - "templating"
    - "sprig-functions"
    - "kubernetes-deployment"
    - "value-substitution"
  # Network ports for the application
  ports: [80, 443, 8080]
  port1: 80
  port2: 443
  port3: 8080
  # Helm chart overrides
  name: "helm-overrides-app"  # Maps to .appName in helm chart
  image:
    tag: "v2.1.0"             # Maps to .image.tag in helm chart

# Database configuration for helm chart
database:
  host: "postgres.zarf.local-schmocal" # Maps to .config.database.host in helm chart
  host2: "postgres.zarf.local" # Also maps to .config.database.host, but takes priority because it's mapped afterwards

