apiVersion: v1
kind: Namespace
metadata:
  labels:
    owner: bigbang
  name: bigbang
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: zarf-git-secret
  namespace: bigbang
stringData:
  username: "zarf-git-user"
  password: "###ZARF_SECRET###"
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: zarf
  namespace: bigbang
spec:
  ignore: |
    # exclude file extensions
    /**/*.md
    /**/*.txt
    /**/*.sh
  interval: 5m
  url: http://stuart-gitea-http.git.svc.cluster.local:3000/zarf-git-user/mirror__github.com__defenseunicorns__zarf.git
  secretRef:
    name: zarf-git-secret
  ref:
    branch: master
#    tag: 1.21.0
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: bigbang
  namespace: bigbang
spec:
  interval: 5m
  path: "./examples/big-bang/template/bigbang"
  prune: true
  sourceRef:
    kind: GitRepository
    name: zarf
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: bigbang
      name: bigbang
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: bigbang
      name: cluster-auditor
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: bigbang
      name: eck-operator
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: bigbang
      name: ek
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: bigbang
      name: fluent-bit
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: bigbang
      name: gatekeeper
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: bigbang
      name: istio
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: bigbang
      name: istio-operator
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: bigbang
      name: jaeger
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: bigbang
      name: kiali
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: bigbang
      name: monitoring
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: bigbang
      name: twistlock
  timeout: 60m
  postBuild:
    substitute:
      zarf_secret: "###ZARF_SECRET###"
