apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: nginx
  labels:
    app: nginx
data:
  01_http.conf: |
    add_header X-Kubernetes-Pod $hostname;
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <title>Welcome to ###ZARF_VAR_SITE_NAME###!</title>
        <style>
          ###ZARF_VAR_STYLE###
        </style>
      </head>
      <body>
        <!-- Test two separate variables on the same line -->
        <h1>Welcome to the ###ZARF_VAR_SITE_NAME###!</h1><h2>Brought to you by ###ZARF_VAR_ORGANIZATION###.</h2>
        <p>Below is a Config File templated by Zarf</p>
        <pre>
          ###ZARF_VAR_MODIFIED_CONFIG###
        </pre>
        <pre>File SHASUM: ###ZARF_VAR_MODIFIED_CONFIG_SHASUM###</pre>
        ###ZARF_VAR_OPTIONAL_FOOTER###
      </body>
    </html>
