serviceAccount:
  name: zarf

clusterRole:
  name: service-viewer

clusterRoleBinding:
  name: service-viewer-binding

role:
  name: zarf-agent

roleBinding:
  name: zarf-agent-binding

secret:
  name: agent-hook-tls
  tlsCrt: "###ZARF_AGENT_CRT###"
  tlsKey: "###ZARF_AGENT_KEY###"

service:
  name: agent-hook

deployment:
  name: agent-hook
  replicaCount: 2

image:
  repository: "###ZARF_REGISTRY###/###ZARF_CONST_AGENT_IMAGE###"
  tag: "###ZARF_CONST_AGENT_IMAGE_TAG###"
  pullSecret: private-registry

resources:
  requests:
    memory: "32Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "500m"

affinity: {}
tolerations: []
