name: Check for go mod changes
on:
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  validate-go-mod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup golang
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod

      - name: Test go mod
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum
