# eksctl create cluster --config-file=eks.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: zarf-nightly-multi-arch-e2e-test
 region: us-east-1
  tags:
    PermissionsBoundary: uds_permissions_boundary

iam:
  serviceRolePermissionsBoundary: arn:aws:iam::205930641482:policy/uds_permissions_boundary
  withOIDC: true

addons:
  - name: aws-ebs-csi-driver
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
    permissionsBoundary: "arn:aws:iam::205930641482:policy/uds_permissions_boundary"
    tags:
      PermissionsBoundary: "uds_permissions_boundary"

  - name: vpc-cni
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
    permissionsBoundary: "arn:aws:iam::205930641482:policy/uds_permissions_boundary"
    tags:
      PermissionsBoundary: "uds_permissions_boundary"

managedNodeGroups:
- instanceType: t3.medium
  name: amd64-ng
  minSize: 2
  maxSize: 2
  spot: true
  tags:
    PermissionsBoundary: "uds_permissions_boundary"
  iam:
    instanceRolePermissionsBoundary: "arn:aws:iam::205930641482:policy/uds_permissions_boundary"
- instanceType: "t4g.small"
  name: arm64-ng
  minSize: 2
  maxSize: 2
  spot: true
  tags:
    PermissionsBoundary: "uds_permissions_boundary"
  iam:
    instanceRolePermissionsBoundary: "arn:aws:iam::205930641482:policy/uds_permissions_boundary"
