name: Large Test

permissions:
  contents: read

on:
  pull_request:

runs-on: large-ubuntu-zarf-release

jobs:
  large-test:
    runs-on: large-ubuntu-zarf-release
    steps:
      # Checkout the repo and setup the tooling for this job
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Setup golang
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version-file: go.mod

      - name: print space
        run: |
          lsblk -f
