name: Validate Docs and Schema
on:
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  validate-docs-and-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup golang
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: go.mod

      - name: Docs and schemas
        run: "make test-docs-and-schema"

      - name: Instruct user to fix
        if: failure()
        run: echo "Please run 'make docs-and-schema' at the root of the repo and commit the changes to your pull request"
