name: Test Site
on:
  pull_request:
  merge_group:

permissions:
  contents: read

# Abort prior jobs in the same workflow / PR
concurrency:
  group: site-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-site:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./site
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0

      - name: npm ci
        run: npm ci

      - name: run site build
        run: npm run build

      - name: check links
        run: npm run link-check
