name: Test Site
on:
  pull_request:
  merge_group:

permissions:
  contents: read

# Abort prior jobs in the same workflow / PR
concurrency:
  group: site-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-site:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./site
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 26

      - name: npm ci
        run: npm ci

      - name: test
        run: npm test

      - name: run site build
        run: npm run build:versions

      - name: check links
        run: npm run link-check
