certificates:
  required: ###ZARF_VAR_GIT_SERVER_TLS_CONFIGURED###
  ca: |
    ###ZARF_VAR_GIT_SERVER_TLS_CA###
  cert: |
    ###ZARF_VAR_GIT_SERVER_TLS_CERT###
  key: |
    ###ZARF_VAR_GIT_SERVER_TLS_KEY###
